bde_ipp/bde_ipp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('register.urls')),
    path('admin/', admin.site.urls),
    path('documents/', include(('documents.urls', 'documents'), namespace='documents'))
]

bde_ipp/documents/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('en/rop', views.rop_en, name='rop_en'),
    path('fr/rop', views.rop_fr, name='rop_fr'),
    path('en/statutes', views.statutes_en, name='statutes_en'),
    path('fr/statutes', views.statutes_fr, name='statutes_fr'),
]

bde_ipp/register/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.register, name='register'),
]

bde_ipp/documents/models.py
from django.db import models

# Create your models here.

bde_ipp/register/models.py
from django.db import models


class Member(models.Model):
    PROGRAMME_TYPES = (
        ('m1', 'Master 1'),
        ('m2', 'Master 2'),
        ('phd', 'PhD track'),
    )

    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    birth_date = models.DateField()
    programme_type = models.CharField(max_length=3, choices=PROGRAMME_TYPES)
    programme_name = models.CharField(max_length=63)
    membership_fee_paid = models.BooleanField(default=False)

bde_ipp/register/forms.py
from django import forms
import datetime

class RegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=32, required=True, label='First Name',widget=forms.TextInput(attrs={'class': 'form-text'}))
    last_name = forms.CharField(max_length=32, required=True, label='Last Name',widget=forms.TextInput(attrs={'class': 'form-text'}))
    email = forms.EmailField(required=True, label='E-mail address',widget=forms.EmailInput(attrs={'class': 'form-text'}))
    address = forms.CharField(max_length=255, required=True, label='Address (Number, Street, Postal Code, Town)',widget=forms.TextInput(attrs={'class': 'form-text'}))
    birth_date = forms.DateField(required=True, label='Date of Birth', initial=datetime.date.today,widget=forms.DateInput(attrs={'class': 'form-text'}))
    programme_type = forms.ChoiceField(required=True, label='Programme',
        choices=[('m1', 'Master 1'), ('m2', 'Master 2'), ('phd', 'PhD track')],widget=forms.Select(attrs={'class': 'form-select form-select-sm'}))
    programme_name = forms.CharField(max_length=63, label='',widget=forms.TextInput(attrs={'class': 'form-text'}))  # Specify exact programme followed
    statutes_rop_agreement = forms.BooleanField(required=True, label=
    """
    I accept and acknowledge the Statutes and the Rules of Procedure of the association.
    I promise to pay my membership fee in accordance with the conditions described in the Rules of Procedure.
    """,widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

bde_ipp/documents/views.py
from django.shortcuts import render

def rop_en(request):
    return render(request, 'documents/rop_en.html')

def rop_fr(request):
    return render(request, 'documents/rop_fr.html')
    
def statutes_en(request):
    return render(request, 'documents/statutes_en.html')

def statutes_fr(request):
    return render(request, 'documents/statutes_fr.html')

bde_ipp/register/views.py
from django.shortcuts import render
from .forms import RegistrationForm
from .models import Member


# Handle account registration
def register(request):
    if request.method == 'POST':
        # Perform checks
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # Save the registration
            new_member = Member()
            new_member.first_name = form.cleaned_data['first_name']
            new_member.last_name = form.cleaned_data['last_name']
            new_member.birth_date = form.cleaned_data['birth_date'] # TODO: ensure no absurd date has been provided!
            new_member.email = form.cleaned_data['email']
            new_member.address = form.cleaned_data['address']
            new_member.programme_type = form.cleaned_data['programme_type']
            new_member.programme_name = form.cleaned_data['programme_name']
            new_member.save()
            return render(request, 'register/success.html')
    else:
        form = RegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'register/register.html', context)

bde_ipp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BDE de l'IP Paris - Online Registration Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
	<!-- Display contents -->
	{% block content %}
    {% endblock %}

	<!--<script src={% static 'assets/js/bootstrap.min.js' %}></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

bde_ipp/templates/documents/statutes_en.html
{% extends 'base.html' %}

{% block content %}

<h1 id="statutes-of-the-bureau-des-elèves-de-linstitut-polytechnique-de-paris">Statutes of the Bureau des Elèves de l’Institut Polytechnique de Paris</h1>
<h2 id="definitions">Definitions</h2>
<ul>
<li><em>IP Paris</em> : Institut Polytechnique de Paris, organisation founded by the decree n° 2019-549 du 31 mai 2019 “portant création de l’établissement public expérimental Institut polytechnique de Paris et approbation de ses statuts”.</li>
<li><em>Board</em> : Board of directors.</li>
<li><em>GA</em> : General Assembly.</li>
<li><em>The association</em> : Bureau des Elèves de l’Institut Polytechnique de Paris.</li>
<li><em>IC</em> : International comittee.</li>
<li><em>Internationals</em> : Person who does not have the French nationality or who spent their entire higher education outside of France.</li>
</ul>
<h2 id="article-1---name">Article 1 - Name</h2>
<p>Is founded between the adherents to the present statutes an association conforming to the law of July 1st 1901 and the decree of August 16th 1901, having the name “Bureau des Elèves de l’Institut Polytechnique de Paris”.</p>
<h2 id="article-2---goals">Article 2 - Goals</h2>
<p>The goals of the association are : - Representing the students of IP Paris - Helping and welcoming incoming students - Organising and promoting student life in IP Paris - Enabling students to have a sense of belonging to IP Paris</p>
<h2 id="article-3---head-office">Article 3 - Head office</h2>
<p>The head office is located 23 Rue Fustel de Coulanges, 91300 Massy. It can be transfered by a simple decision of the Board.</p>
<h2 id="article-4---lifespan">Article 4 - Lifespan</h2>
<p>The lifespan of the association is unlimited.</p>
<h2 id="article-5---composition">Article 5 - Composition</h2>
<p>The association is composed of student members.</p>
<h2 id="article-6---admission">Article 6 - Admission</h2>
<p>Any physical person registered as a student at the IP Paris can be a student member. A person paying the membership fee agreed upon in the rules of procedure and following the aforementioned requirements becomes a member student.</p>
<h2 id="article-7---revocation">Article 7 - Revocation</h2>
<p>The membership can be lost by : - Resignation. - Death. - Removal by the board following an unpaid membership fee or for serious misconduct, the interested party having been asked to answer for their misconduct before the executives and/or in writing.</p>
<h2 id="article-8---affiliation">Article 8 - Affiliation</h2>
<p>The association can become a member of other associations, unions or groups by a decision from the Board.</p>
<h2 id="article-9---resources">Article 9 - Resources</h2>
<p>The financial resources of the association are : - The membership fees. - Subsidies from the government, local administrations and other public organisations. - The sales of goodies, including, but not limited to : pen, mugs, clothes. - All resources allowed by the applicable laws and regulations.</p>
<h2 id="article-10---ordinary-general-assembly">Article 10 - Ordinary General Assembly</h2>
<p>The general assembly is composed of all members of the association in whatever capacity.</p>
<p>It is summoned at least once a year by the board or by a quarter of its members.</p>
<p>Fifteen days before the date of the assembly, the members of the association are summoned by the secretary. The agenda is mentioned in the summons. All members of the GA may add an item on the agenda until seven days before the GA.</p>
<p>The president, who can be helped by board members, presides the assembly and presents the situation or the activities of the association. The treasurer reports their management, and submits the annual accounts (balance sheet, financial results and appendix) to be approved by the assembly.</p>
<p>Only items mentioned on the agenda can be raised during the assembly.</p>
<p>Decisions are made according to the majority of votes of present and represented members.</p>
<p>After the agenda is depleted of all items, the election of the Board and of the executives is held.</p>
<p>The rules of procedure infers the terms of the elections and of the voting procedure.</p>
<h2 id="article-11---extraordinary-general-assembly">Article 11 - Extraordinary General Assembly</h2>
<p>If needed, or if half the members plus one asks, the board can summon an extraordinary GA abiding by the terms of the present statutes, only for the amendment of the statutes or to dissolve the association or for decisions involving immovable property. The procedure for the summoning are the same as the ordinary GA. All decisions are made by a qualified majority of two thirds of the present members.</p>
<h2 id="article-12---board-of-directors">Article 12 - Board of Directors</h2>
<p>The association is run by a board of directors elected for one year. Directors cannot be reelected.</p>
<p>The GA elects a minimum of 5 members and a maximum of 20 members to the board. These members are called ordinary members.</p>
<p>The IC appoints, after the elections of ordinary members to the board, members of which the number cannot exceed a fifth of the number of ordinary members, rounded up. These members are called invited members.</p>
<p>In the case of vacancies, the board appoints members to the vacant positions. The final replacement is made at the closest GA. The powers of the members appointed this way expire at the end of the mandates of the replaced members.</p>
<p>The board meets at least once every three months, on a summon by the president, or through the demand of a quarter of its members. The board can meet more often than specified.</p>
<p>The decisions are taken according to the majority of the votes of ordinary members. In case of a tie, the votes of invited members are taken into account. If a tie remains, the president has the last say.</p>
<p>A director who, without reason, did not attend three consecutive board meetings is considered to be resigning from their position.</p>
<p>The rules of procedure decribe the voting and summoning procedures of the board.</p>
<p>The board has the most extensive powers over the association.</p>
<h2 id="article-13---executives">Article 13 - Executives</h2>
<p>The GA elects the following executives: - A president and, if needed, a vice-president. - A secretary and, if needed, a vice-secretary. - A treasurer and, if needed, a vice-treasurer.</p>
<p>The executives are part of the ordinary members of the board elected by the GA.</p>
<p>The rules of procedure describe the roles and powers of the executives.</p>
<h2 id="article-14---the-international-comittee">Article 14 - The International comittee</h2>
<p>The association has a comittee of at least 3 international members looking after the interests of international students of the IP Paris.</p>
<p>The members of the IC are elected by the international members of the association for a mandate of one year and cannot be reelected.</p>
<p>The details and procedures of the elections are described in the rules of procedure.</p>
<p>The procedure of appointment by the IC of the invited members is laid out in the rules of procedure.</p>
<p>The IC elects a president according to a procedure detailed in the rules of procedure.</p>
<p>The IC meets at least once every three months on the summon of the president of the association or of the president of the IC.</p>
<h2 id="article-15---indemnification">Article 15 - Indemnification</h2>
<p>All positions, including that of the board members, executives and IC members are unpaid and voluntary. Only costs associated with their mandates can be paid back on proof of spending. The financial report presented to the GA lays out, by beneficiary, the amount paid back for mission costs, travel expenses, or representation costs.</p>
<h2 id="article-16---rules-of-procedure">Article 16 - Rules of procedure</h2>
<p>Rules of procedure are written by the board.</p>
<p>The GA may decide to amend the rules of procedure.</p>
<p>The rules of procedure are intended to add precisions on what wasn’t specified by the present statutes, especially those pertaining to the internal running of the association.</p>
<p>The rules of procedure define items delegated by the present statutes.</p>
<h2 id="article-17---dissolution">Article 17 - Dissolution</h2>
<p>In the event of a dissolution decided according to the dispositions of article 11, one or several liquidators are appointed and the net assets, if necessary, are donated to an association following similar goals, according to the decision of the extraordinary GA that voted the dissolution. The net assets cannot be allocated, even partially, to a member of the association.</p>
<h2 id="article-18---initial-members">Article 18 - Initial members</h2>
<p>The signatories of the present statutes or those appointed by them are put in the positions specified by the signatures or the appointment, regardless of the other articles, for the duration specified by those articles. The signatories can only appoint members for the 3 months following the signature of the statutes.</p>
<h2 id="article-19---work-languages">Article 19 - Work languages</h2>
<p>English and French are the work languages of the association. Meeting minutes, statutes, rules of procedure and all communication material intended for the members must be available in both languages.</p>

{% endblock %}

bde_ipp/templates/documents/statutes_fr.html
{% extends 'base.html' %}

{% block content %}

<h1 id="statuts-du-bureau-des-elèves-de-linstitut-polytechnique-de-paris">Statuts du Bureau des Elèves de l’Institut Polytechnique de Paris</h1>
<h2 id="définitions">Définitions</h2>
<ul>
<li><em>IP Paris</em> : Institut Polytechnique de Paris, établissement fondé par le décret n° 2019-549 du 31 mai 2019 portant création de l’établissement public expérimental Institut polytechnique de Paris et approbation de ses statuts.</li>
<li><em>CA</em> : Conseil d’Administration.</li>
<li><em>AG</em> : Assemblée Générale.</li>
<li><em>L’association</em> : Bureau des Elèves de l’Institut Polytechnique de Paris.</li>
<li><em>CI</em> : Comité International.</li>
<li><em>Internationaux</em> : Personne n’ayant pas la nationalité Française ou ayant passé l’intégralité de son enseignement supérieur hors de France.</li>
</ul>
<h2 id="article-1---nom">Article 1 - Nom</h2>
<p>Il est fondé entre les adhérents aux présents statuts une association régie par la loi du 1er juillet 1901 et le décret du 16 août 1901, ayant pour titre Bureau des Elèves de l’Institut Polytechnique de Paris.</p>
<h2 id="article-2---objet">Article 2 - Objet</h2>
<p>Cette association a pour objets : - La représentation des étudiants de l’IP Paris. - L’aide et l’accueil des nouveaux étudiants. - L’organisation et la promotion de la vie associative dans l’IP Paris. - Créer un sentiment d’appartenance à l’IP Paris chez les étudiants.</p>
<h2 id="article-3---siège-social">Article 3 - Siège social</h2>
<p>Le siège social est fixé au 23 Rue Fustel de Coulanges, 91300 Massy. Il pourra être transféré sur simple décision du CA.</p>
<h2 id="article-4---durée">Article 4 - Durée</h2>
<p>La durée de l’association est illimitée.</p>
<h2 id="article-5---composition">Article 5 - Composition</h2>
<p>L’association se compose de membres étudiants.</p>
<h2 id="article-6---admission">Article 6 - Admission</h2>
<p>Peut être membre étudiant toute personne physique inscrite comme étudiante dans l’IP Paris. Deviennent membres étudiants les personnes versant une cotisation fixée par le règlement intérieur et respectant les conditions citées au premier alinéa.</p>
<h2 id="article-7---radiations">Article 7 - Radiations</h2>
<p>La qualité de membre se perd par : - La démission. - Le décès. - La radiation prononcée par le conseil d’administration pour non-paiement de la cotisation ou pour motif grave, l’intéressé ayant été invité à fournir des explications devant le bureau et/ou par écrit.</p>
<h2 id="article-8---affiliation">Article 8 - Affiliation</h2>
<p>L’association peut adhérer à d’autres associations, unions ou regroupements par décision du conseil d’administration.</p>
<h2 id="article-9---ressources">Article 9 - Ressources</h2>
<p>Les ressources de l’association comprennent : - Le montant des droits d’entrée et des cotisations. - Les subventions de l’Etat, des départements, des communes, et d’autres établissements publics. - La vente d’objets de communication incluant mais non limités à : stylos, tasses, vêtements. - Toutes les ressources autorisées par les lois et règlements en vigueur.</p>
<h2 id="article-10---assemblée-générale-ordinaire">Article 10 - Assemblée Générale Ordinaire</h2>
<p>L’assemblée générale ordinaire comprend tous les membres de l’association à quelque titre qu’ils soient.</p>
<p>Elle se réunit au moins une fois par an sur convocation par le CA ou sur demande du quart de ses membres.</p>
<p>Quinze jours au moins avant la date fixée, les membres de l’association sont convoqués par les soins du secrétaire. L’ordre du jour figure sur les convocations. Tout membre de l’AG peut demander l’ajout d’un point à l’ordre du jour jusqu’à sept jours avant la tenue de l’assemblée.</p>
<p>Le président, assisté des membres du conseil, préside l’assemblée et expose la situation morale ou l’activité de l’association. Le trésorier rend compte de sa gestion et soumet les comptes annuels (bilan, compte de résultat et annexe) à l’approbation de l’assemblée.</p>
<p>Ne peuvent être abordés que les points inscrits à l’ordre du jour.</p>
<p>Les décisions sont prises à la majorité des voix des membres présents ou représentés.</p>
<p>Il est procédé, après épuisement de l’ordre du jour, au renouvellement des membres ordinaires du CA et du bureau.</p>
<p>Le règlement intérieur fixe les modalités de suffrage et d’élection.</p>
<h2 id="article-11---assemblée-générale-extraordinaire">Article 11 - Assemblée Générale Extraordinaire</h2>
<p>Si besoin est, ou sur la demande de la moitié plus un des membres, le CA peut convoquer une assemblée générale extraordinaire, suivant les modalités prévues par les présents statuts, et uniquement pour modification des statuts, la dissolution ou pour des actes portant sur des immeubles. Les modalités de convocation sont les mêmes que pour l’assemblée générale ordinaire. Les délibérations sont prises à la majorité qualifiée aux deux tiers des membres présents.</p>
<h2 id="article-12---conseil-dadministration">Article 12 - Conseil D’Administration</h2>
<p>L’association est dirigée par un conseil de membres élus pour une durée d’un an. Les membres ne sont pas rééligibles.</p>
<p>L’AG élit un minimum de 5 membres et un maximum de 20 membres au CA. Ces membres sont appelés membres ordinaires.</p>
<p>Sont désignées par le CI, après l’élection des membres ordinaires du CA, des membres dont le nombre ne peux dépasser un cinquième du nombre de membres ordinaires, arrondi à l’unité supérieure. Ces membres sont appelés membres invités.</p>
<p>En cas de vacances, le conseil pourvoit provisoirement au remplacement de ses membres. Il est procédé à leur remplacement définitif par la plus prochaine assemblée générale. Les pouvoirs des membres ainsi élus prennent fin à l’expiration du mandat des membres remplacés.</p>
<p>Le conseil d’administration se réunit au moins une fois tous les trois mois, sur convocation du président, ou à la demande du quart de ses membres. Les réunions du conseil peuvent être plus fréquentes.</p>
<p>Les décisions sont prises à la majorité des voix des membres ordinaires ; en cas de partage, sont comptées les voix des membres invités; s’il y a toujours partage, la voix du président est prépondérante.</p>
<p>Tout membre du conseil qui, sans excuse, n’aura pas assisté à trois réunions consécutives sera considéré comme démissionnaire.</p>
<p>Le règlement intérieur précise les modalités de réunion et de suffrage du CA.</p>
<p>Le CA dispose des pouvoir les plus étendus sur l’association.</p>
<h2 id="article-13---le-bureau">Article 13 - Le Bureau</h2>
<p>L’AG élit un bureau composé de : - Un-e- président-e- et, s’il y a lieu, un-e- vice-président-e-s. - Un-e- secrétaire et, s’il y a lieu, un-e- secrétaire adjoint-e-. - Un-e- trésorier-e-, et, si besoin est, un-e- trésorier-e- adjoint-e-.</p>
<p>Le bureau fait partie des membres ordinaires du CA élus par l’AG.</p>
<p>Le règlement intérieur fixe les rôles et prérogatives du bureau.</p>
<h2 id="article-14---le-comité-intérnational">Article 14 - Le Comité Intérnational</h2>
<p>L’association dispose d’un comité d’au moins 3 membres internationaux veillant à l’intéret des étudiants internationaux de l’IP Paris.</p>
<p>Les membres du CI sont élus par les membres étudiants internationaux de l’association pour une durée de un an et ne sont pas rééligibles.</p>
<p>Les modalités de l’élection sont fixées par le règlement intérieur.</p>
<p>Les modalités de désignation par le CI des membres invités sont fixées par le règlement intérieur.</p>
<p>Le CI élit un président selon des modalités fixées par le règlement intérieur.</p>
<p>Le CI se réunit au moins une fois tous les 3 mois sur convocation par le président de l’association ou par le président du CI.</p>
<h2 id="article-15---indemnités">Article 15 - Indemnités</h2>
<p>Toutes les fonctions, y compris celles des membres du CA, du bureau et du CI, sont gratuites et bénévoles. Seuls les frais occasionnés par l’accomplissement de leur mandat sont remboursés sur justificatifs. Le rapport financier présenté à l’assemblée générale ordinaire présente, par bénéficiaire, les remboursements de frais de mission, de déplacement ou de représentation.</p>
<h2 id="article-16---règlement-intérieur">Article 16 - Règlement Intérieur</h2>
<p>Un règlement intérieur est établi par le CA.</p>
<p>L’AG peut décider de modifier le règlement intérieur.</p>
<p>Ce règlement est destiné à fixer les divers points non prévus par les présents statuts, notamment ceux qui ont trait à l’administration interne de l’association.</p>
<p>Ce règlement fixe les points que les présents statuts lui délèguent.</p>
<h2 id="article-17---dissolution">Article 17 - Dissolution</h2>
<p>En cas de dissolution prononcée selon les modalités prévues à l’article 11, un ou plusieurs liquidateurs sont nommés, et l’actif net, s’il y a lieu, est dévolu à une association ayant des buts similaires conformément aux décisions de l’AG extraordinaire qui statue sur la dissolution. L’actif net ne peut être dévolu à un membre de l’association, même partiellement.</p>
<h2 id="article-18---membres-initiaux">Article 18 - Membres initiaux</h2>
<p>Les signataires des présents statuts ou ceux désignés par ceux-ci sont établis aux fonctions précisées par les signatures ou par la désignation en dépit des dispositions des autres articles pour les durées précisées par ces articles. Les signataires des présents statuts ne peuvent désigner de membres que pendant un délai de 3 mois à compter de la signature des statuts.</p>
<h2 id="article-19---langues-de-travail">Article 19 - Langues de travail</h2>
<p>Les langues de travail de l’association sont l’Anglais et le Français. Les comptes-rendus, les statuts, le règlement intérieur, et tous les documents de communication aux membres devront être disponibles aux membres dans les deux langues.</p>
<p>Fait à Massy, le 19 semptembre 2021.</p>

{% endblock %}

bde_ipp/templates/register/register.html
{% extends 'base.html' %}

{% block content %}

<h1>BDE IP Paris - Registration form</h1>

<form method="post" action="{% url 'register' %}">
    {% csrf_token %}

    {{ form.non_field_errors }}
    <div class="fieldWrapper row justify-content-center">
        {{ form.first_name.errors }}
        <div class="col-3">
            <label for="{{ form.first_name.id_for_label }}">{{form.first_name.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.first_name }}
        </div>
    </div>
    <div class="fieldWrapper row justify-content-center">
        {{ form.last_name.errors }}
        <div class="col-3">
            <label for="{{ form.last_name.id_for_label }}">{{form.last_name.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.last_name }}
        </div>
    </div>
    <div class="fieldWrapper row justify-content-center">
        {{ form.birth_date.errors }}
        <div class="col-3">
            <label for="{{ form.birth_date.id_for_label }}">{{form.birth_date.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.birth_date }}
        </div>
    </div>
    <div class="fieldWrapper row justify-content-center">
        {{ form.email.errors }}
        <div class="col-3">
            <label for="{{ form.email.id_for_label }}">{{form.email.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.email }}
        </div>
    </div>
    <div class="fieldWrapper row justify-content-center">
        {{ form.address.errors }}
        <div class="col-3">
            <label for="{{ form.address.id_for_label }}">{{form.address.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.address }}
        </div>
    </div>
    <div class="fieldWrapper row justify-content-center">
        {{ form.programme_type.errors }}
        <div class="col-3">
            <label for="{{ form.programme_type.id_for_label }}">{{form.programme_type.label}}:</label>
        </div>
        <div class="col-2">
            {{ form.programme_type }} {{ form.programme_name }}
        </div>
    </div>

    <div class="fieldWrapper row justify-content-center">
        <div class="col">
        {{ form.statutes_rop_agreement.errors }}
        {{ form.statutes_rop_agreement }}
        <label for="{{ form.statutes_rop_agreement.id_for_label }}">{{ form.statutes_rop_agreement.label }}</label>
        </div>
    </div>

    <div class="row justify-content-center">
        <p>Links to the <a href="{% url 'documents:statutes_en' %}">statutes</a> (<a href="{% url 'documents:statutes_fr' %}">statuts</a>) and the <a href="{% url 'documents:rop_en' %}">rules of procedure</a> (<a href="{% url 'documents:rop_fr' %}">règlement intérieur</a>).</p>
    </div>

    <div class="fieldWrapper">
        <input type="submit" value="Submit" class="btn btn-primary"/>
    </div>
</form>

{% endblock %}
{% url 'register' %}

bde_ipp/templates/register/success.html
{% extends 'base.html' %}

{% block content %}

<h1>BDE IP Paris - Registration successful!</h1>

<p>You shall get contacted soon by e-mail for further information on the payment of your membership fee.</p>

{% endblock %}